### ISSUE TITLE
i want to give a start but i won't... :) such a paradox😁

### ISSUE THREAD

**Issue by alirezainjasttt** [RealPeha/This-Repo-Has-1157-Stars#5]

**Comment by fellahi-ali** [comment]
the first thing I did is starring... to see what would happen

**Comment by alirezainjasttt** [comment]
now i get it... so fun.

**Comment by jinfagang** [comment]
I can not comment

**Comment by jinfagang** [comment]
![image](https://user-images.githubusercontent.com/21303438/108673163-2b3fc400-751e-11eb-9631-c92a17b85031.png)
